### ISSUE TITLE
File names with Japanese Characters won't extract

### ISSUE THREAD

**Issue by FM1337** [Shizmob/rpatool#1]
When attempting to extract from an archive that contains files with Japanese characters in their file name it skips these files.

This happens on Windows and Ubuntu

**Comment by Shizmob** [comment]
Hi! Thanks for the issue report.

I just put a commit that I think fixes your issue, could you give it a shot?

**Comment by FM1337** [comment]
Alright so after trying it, it did indeed work.

Thanks for fixing the issue I was worried that you no longer supported it
as on your website it said that it was a completed project

but again thanks for fixing it mate.

**Comment by Shizmob** [comment]
My website does say that even completed projects will still get bugfixes and some minor features.
Glad rpatool was useful to you!

**Comment by FM1337** [comment]
Ah, I missed that my apologies, I'm a bit tired today I was up for the most
of the night debugging this and trying to see if I could find a fix.
