### ISSUE TITLE
Extract error

### ISSUE THREAD

**Issue by ssc41** [Shizmob/rpatool#16]
Tried to extact a rpa file but got the error 'bytes' object has no attribute 'encode'

Fixed it by changing _unmangle to this:
        return data.encode('latin1') if hasattr(data,"encode") else data

**Comment by BreathHolder** [comment]
perfect fix for this error:

`Could not extract file scripts\script01.rpyc from archive: 'bytes' object has no attribute 'encode'`

**Comment by shizmob** [comment]
This should be fixed with #13 merged!
