### ISSUE TITLE
I cannot extract the .extra content of a game in Ren'Py

### ISSUE THREAD

**Issue by nicker7** [Shizmob/rpatool#17]
I'm trying to extract some images from the game to translate into my language, but it gives error.

`-desktop:~/Jogos/ExtraLife-0.5.9-pc/game$ python3 rpatool.py -x data.extra
Traceback (most recent call last):
  File "rpatool.py", line 383, in <module>
    archive = RenPyArchive(archive, padlength=padding, key=key, version=version, verbose=arguments.verbose)
  File "rpatool.py", line 85, in __init__
    self.load(file)
  File "rpatool.py", line 249, in load
    self.version = self.get_version()
  File "rpatool.py", line 96, in get_version
    magic = self.handle.readline().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 3: invalid continuation byte
`

Can you tell me if there is any solution for this?

**Comment by shizmob** [comment]
This looks like a modified archive, it's hard to pin-point the specific error that way.
It looks like this archive belongs to a commercial VN, in which case I'd like to point you to the following part of the `README`:
```
the unpermitted use on files where such consent was not given is highly discouraged, and most likely a license violation as well. Support requests for help with dealing with such files will not be answered.
```
