### ISSUE TITLE
How do I use this tool?

### ISSUE THREAD

**Issue by ElwoodHogan** [Shizmob/rpatool#18]
Ive tried using it though command prompt and through python, but niether have worked.  Am i missing something?

**Comment by UniverseDevel** [comment]
Maybe start by mentioning what OS you are running on and which Python version are you using. Also some examples of exact commands you are trying to run would not hurt.

**Comment by shizmob** [comment]
Closing due to lack of response, thanks for the help, @UniverseDevel!
