### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by alexcantfunction** [Shizmob/rpatool#20]
Hey im really sorry but im like completly new to everything and even though ive tried to read and figure out by myself what to do to not bother people i still cant get it right :(. Like I said I know nothing about this other than someone recommended me to use this to pack a rpa file. I have python installed and i put the rpatool file in the directory i wanted, i opened a command tab on the directory but when i put this command "rpatool -c archive.rpa archive" I get the error "'rpatool' is not recognized as an internal or external command,
operable program or batch file", I would really appreciate the help and sorry if this is a dumb question!

**Comment by UniverseDevel** [comment]
https://www.wikihow.com/Use-Windows-Command-Prompt-to-Run-a-Python-File

**Comment by alexcantfunction** [comment]
> https://www.wikihow.com/Use-Windows-Command-Prompt-to-Run-a-Python-File

THANK YOU SO MUCH!! I was able to do it now <3

**Comment by UniverseDevel** [comment]
@Shizmob can be closed

**Comment by shizmob** [comment]
Thanks @UniverseDevel!
