### ISSUE TITLE
zlib.error: Error -3 while decompressing data: incorrect header check?

### ISSUE THREAD

**Issue by 0bsidi4n** [Shizmob/rpatool#3]
Not sure what to ask here, but this is the error I get.

Traceback (most recent call last):
File "rpatool.py", line 307, in <module>
File "rpatool.py", line 30, in __init__
File "rpatool.py", line 176, in load
File "rpatool.py", line 66, in extract_indexes
File "encodings\zlib_codec.pyc", line 43, in zlib_decode
zlib.error: Error -3 while decompressing data: incorrect header check

Thanks

**Comment by trixymoon** [comment]
I've got the same error with rpa archive made with the last version of renpy..

**Comment by Shizmob** [comment]
I see nothing changed in the last version of Ren’Py - could you two provide me with a sample through hi@shiz.me <mailto:hi@shiz.me>?

**Comment by Shizmob** [comment]
I just pushed a commit that fixed a potentially faulty assumption rpatool was making about the metadata format (but one that Ren’Py also makes).

Could you verify if it works with this version? Thanks!

**Comment by trixymoon** [comment]
I can confirm too. It's working flawlessly. Thanks :-)

**Comment by Shizmob** [comment]
Great, thanks for reporting!
